apiVersion: v1
kind: Service
metadata:
  name: {{ include "jira.fullname" . }}
  labels:
    {{- include "jira.labels" . | nindent 4 }}
spec:
  ports:
    # port is what this service should serve on, and targetPort is the port in the container.
    - port: {{ .Values.jira.service.port }}
      name: jira-main
      targetPort: jiraport
      protocol: TCP
#    - port: 8888
#      name: jira-internal-connector
#      targetPort: 8888
#      protocol: TCP
    - port: 40001
      name: rmi
      protocol: TCP
      targetPort: jiraclusterport
    - port: 40011
      name: remote-object
      protocol: TCP
      targetPort: remote-object
  clusterIP: None
  selector:
    {{- include "jira.selectorLabels" . | nindent 4 }}
