apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    # port is what this service should serve on, and targetPort is the port in the container.
    - port: {{ .Values.jira.service.port }}
      name: jira-main
      targetPort: jiraport
      protocol: TCP
#    - port: 8888
#      name: jira-internal-connector
#      targetPort: 8888
#      protocol: TCP
    - port: {{ .Values.cluster.clusterPort }}
      name: rmi
      protocol: TCP
      targetPort: jiraclusterport
    - port: {{ .Values.cluster.ehcachePort }}
      name: remote-object
      protocol: TCP
      targetPort: remote-object
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
