apiVersion: apps/v2
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
spec:
  serviceName: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          ports:
            - containerPort: {{ .Values.jira.ports.jiraport }}
              name: jiraport
            - containerPort: {{ .Values.cluster.clusterPort }}
              name: jiraclusterport
            - containerPort: {{ .Values.cluster.ehcachePort }}
              name: remote-object
          env:
            - name: JIRA_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EHCACHE_LISTENER_HOSTNAME
              value: "$(JIRA_NODE_ID).{{ .Chart.Name }}.default.svc.cluster.local"
          envFrom:
            - configMapRef:
                name: jira-dc-config
          volumeMounts:
            - mountPath: {{ .Values.volumes.home.mountPath | quote }}
              name: home
            - mountPath: {{ .Values.volumes.sharedHome.mountPath | quote }}
              name: shared-home
      volumes:
        - name: home
          emptyDir:
            {}
        - name: shared-home
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.sharedHome.volumeClaimName }}
  volumeClaimTemplates:
    - metadata:
        name: home
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.volumes.home.storageClassName | quote }}
        {{- with .Values.volumes.home.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
